const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.AddVar
	];
};
self.C3_JsPropNameTable = [
	{gameBg: 0},
	{infoBg: 0},
	{row: 0},
	{column: 0},
	{placed: 0},
	{Flash: 0},
	{items: 0},
	{Text: 0},
	{posX: 0},
	{posY: 0},
	{DragDrop: 0},
	{Tween: 0},
	{dragItem: 0},
	{AJAX: 0},
	{cevapsJSON: 0},
	{Browser: 0},
	{Audio: 0},
	{infoBtn: 0},
	{startBtn: 0},
	{nextBtn: 0},
	{closeBtn: 0},
	{replayBtn: 0},
	{Touch: 0},
	{Sprite: 0},
	{randomSudoku: 0},
	{CompleteGame: 0}
];

self.InstanceType = {
	gameBg: class extends self.ISpriteInstance {},
	infoBg: class extends self.ISpriteInstance {},
	items: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	dragItem: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	cevapsJSON: class extends self.IJSONInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	infoBtn: class extends self.ISpriteInstance {},
	startBtn: class extends self.ISpriteInstance {},
	nextBtn: class extends self.ISpriteInstance {},
	closeBtn: class extends self.ISpriteInstance {},
	replayBtn: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {}
}